"""Audit and Prompt Version Agent — records every change with prompt version, commit, test results."""
import json
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from src.utils.logger import get_logger

logger = get_logger(__name__)

PROMPTS_DIR = Path("prompts/prompt_versions")
CHANGELOG_PATH = Path("docs/CHANGELOG.md")


def _get_git_commit_hash() -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, timeout=5,
        )
        return result.stdout.strip() or "unknown"
    except Exception:
        return "unknown"


class AuditAgent:
    """
    Records every significant change to a versioned prompt file and CHANGELOG.

    Call `record_change()` after every code deployment or prompt update.
    """

    def _next_version(self) -> str:
        PROMPTS_DIR.mkdir(parents=True, exist_ok=True)
        existing = sorted(PROMPTS_DIR.glob("prompt_v*.md"))
        if not existing:
            return "v2"
        last = existing[-1].stem  # e.g. "prompt_v3"
        num = int(last.replace("prompt_v", "")) + 1
        return f"v{num}"

    def record_change(
        self,
        changed_files: List[str],
        reason: str,
        unit_test_result: str = "pending",
        backtest_result: Optional[str] = None,
        author: str = "system",
    ) -> Dict[str, Any]:
        """
        Saves a new prompt version file and appends to CHANGELOG.

        Args:
            changed_files: List of file paths changed
            reason: Human-readable reason for the change
            unit_test_result: "passed" / "failed" / "pending"
            backtest_result: Optional backtest summary
            author: Who made the change
        """
        version = self._next_version()
        commit = _get_git_commit_hash()
        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        prompt_content = f"""# Prompt {version}
**Date:** {timestamp}
**Git Commit:** {commit}
**Author:** {author}

## Changed Files
{chr(10).join(f"- {f}" for f in changed_files)}

## Reason for Change
{reason}

## Unit Test Result
{unit_test_result}

## Backtest Result
{backtest_result or "N/A"}

---
*Auto-generated by AuditAgent*
"""
        prompt_path = PROMPTS_DIR / f"prompt_{version}.md"
        prompt_path.write_text(prompt_content)
        logger.info("Prompt version %s saved to %s", version, prompt_path)

        # Append to CHANGELOG
        changelog_entry = (
            f"\n## [{version}] {timestamp} — {reason[:80]}\n"
            f"**Commit:** {commit}  \n"
            f"**Files:** {', '.join(changed_files)}  \n"
            f"**Tests:** {unit_test_result}  \n"
        )
        if CHANGELOG_PATH.exists():
            existing = CHANGELOG_PATH.read_text()
            # Insert after the header line
            lines = existing.split("\n")
            insert_at = next((i for i, l in enumerate(lines) if l.startswith("## [")), len(lines))
            lines.insert(insert_at, changelog_entry)
            CHANGELOG_PATH.write_text("\n".join(lines))
        else:
            CHANGELOG_PATH.write_text(f"# Changelog\n{changelog_entry}")

        return {
            "version": version,
            "commit": commit,
            "prompt_file": str(prompt_path),
            "changelog_updated": True,
        }
